module.exports.allEmailsList = [
    {
      userEmail: 'dan@test.com',
      password: '12345',
      emailsList: [
        {
          id: 001,
          sender: 'git@test.com',
          reciever: 'dan@test.com',
          message: 'hello!!!!',
          subject: 'this is test number 1',
          creation_date: 1603464807000,
        },
        {
          id: 002,
          sender: 'lola@test.com',
          reciever: 'dan@test.com',
          message: 'hello 222!!!!',
          subject: 'this is test number 2',
          creation_date: 1603464807000,
        },
        {
          id: 003,
          sender: 'luka@test.com',
          reciever: 'dan@test.com',
          message: 'test!!!!!!!!!!',
          subject: 'this is test number 3',
          creation_date: 1603464807000,
        },
        {
          id: 004,
          sender: 'lexie@test.com',
          reciever: 'dan@test.com',
          message: 'test 333!!!!!!!!!!',
          subject: 'this is test number 4',
          creation_date: 1603464807000,
        },
        {
          id: 005,
          sender: 'dan@test.com',
          reciever: 'lexie@test.com',
          message: 'test 444!!!!!!!!!!',
          subject: 'this is test number 5',
          creation_date: 1603464807000,
        },
      ],
    },
    {
      userEmail: 'lexie@test.com',
      password: '4455aa',
      emailsList: [
        {
          id: 006,
          sender: 'lexie@test.com',
          reciever: 'dan@test.com',
          message: 'test 333!!!!!!!!!!',
          subject: 'this is test number 4',
          creation_date: 1603464807000,
        },
        {
          id: 007,
          sender: 'dan@test.com',
          reciever: 'lexie@test.com',
          message: 'test 444!!!!!!!!!!',
          subject: 'this is test number 5',
          creation_date: 1603464807000,
        },
      ],
    },
  ]